apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/chanducherry911/Jenkins-Zero-To-Hero.git
    targetRevision: main
    path: java-maven-sonar-argocd-helm-k8s/helm/spring-boot-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: spring-boot-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
